# This is a basic workflow to help you get started with Actions

name: ct2

# Controls when the action will run.
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the main branch
  # schedule:
    # - cron:  '0 0,6,12,18 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Start Ct
        run: |
          mkdir -p downloads/torrents
          #docker run -d -p 80:3000 -p 5007:50007 -v $PWD/downloads:/downloads -v $PWD/downloads/torrents:/torrents boypt/cloud-torrent:1.2.12
          #docker run -d -p 80:3000 -p 5007:50007 -v $PWD/downloads:/downloads -v $PWD/downloads/torrents:/torrents -v /mnt:/downloads/1 823464517/ct:1.2.12
          #sudo wget -O github-ct.rar https://raw.githubusercontent.com/zhouzhenqi/file/master/github-ct.rar
          sudo apt update
          #sudo apt install -y unrar
          #sudo unrar x github-ct.rar
          sudo curl -O https://raw.githubusercontent.com/zhouzhenqi/file/master/ct2.tar.xz
          sudo sleep 1
          sudo xz -z -d ct2.tar.xz
          sudo tar -xvf ct2.tar
          sudo mv cloudtorrent/ /etc/
          cd /etc/cloudtorrent/
          sudo chmod 777 *
          docker run -d --network host -v $PWD/downloads:/downloads -v $PWD/downloads/torrents:/torrents -v /mnt:/downloads/1  -v /etc/cloudtorrent:/etc/cloudtorrent/ 823464517/ct:ubuntu
          docker ps
          #name=$(cat /etc/hostname)
          #pport=$(echo $name | awk -F- '{print $3}')
          sudo sed -i 's#local_port = 80#local_port = 3000#g' /etc/cloudtorrent/frpc.ini
          sudo sed -i "s/tcp-22/"$name"-tcp-22/g" /etc/cloudtorrent/frpc.ini
          sudo sed -i "s/52222/52"$pport"/g" /etc/cloudtorrent/frpc.ini
          sudo sed -i "s/p2p_ssh/"$name"-ssh/g" /etc/cloudtorrent/frpc.ini
          sudo sed -i "s/p2p_80/"$name"-p2p_3000/g" /etc/cloudtorrent/frpc.ini
          #sudo sed -i "s/http-80/"$name"-80/g" /etc/cloudtorrent/frpc.ini
          #sudo sed -i "s/tcp-5007/"$name"-5007/g" /etc/cloudtorrent/frpc.ini
          #sudo sed -i "s/udp-5007/"$name"-u5007/g" /etc/cloudtorrent/frpc.ini
          #sudo sed -i "s/6080/6"$pport"/g" /etc/cloudtorrent/frpc.ini
          #sudo sed -i "s/5007/5"$pport"/g" /etc/cloudtorrent/frpc.ini
          #sudo sed -i "s/5007/5"$pport"/g" /etc/cloudtorrent/cloud-torrent.yaml
          #sudo sed -i "s/local_ip = 0.0.0.0/local_ip = 172.17.0.2/g" /etc/cloudtorrent/frpc.ini
          #sudo ./runct.sh &
          
      # Runs a set of commands using the runners shell
      - name: Start frpc
        run: |
          sudo wget https://github.com/fatedier/frp/releases/download/v0.40.0/frp_0.40.0_linux_amd64.tar.gz
          sudo tar -xf frp_0.40.0_linux_amd64.tar.gz --strip-components 1 -C .
          sudo cp /etc/cloudtorrent/frpc.ini ./frpc-run.ini
          sudo rm -rf /opt/*
          sudo rm -rf /usr/local/julia1.7.1/
          sudo rm -rf ./usr/local/share/chromium/
          sudo apt -y auto-remove php7.4
          sudo apt -y auto-remove php8.0
          sudo apt -y auto-remove php8.1
          sudo rm -rf ./usr/local/graalvm/
          sudo rm -rf ./usr/local/.ghcup/
          sudo rm -rf ./usr/local/lib/android/
          sudo rm -rf ./usr/lib/jvm/
          sudo rm -rf ./usr/lib/firefox/
          sudo rm -rf ./usr/lib/google-cloud-sdk/
          sudo rm -rf /usr/share/swift/
          sudo swapoff -v /mnt/swapfile
          sudo rm -rf /mnt/swapfile
          sudo rm -rf /home/linuxbrew/
          sudo ./frpc -c frpc-run.ini
